### ISSUE TITLE
DATE PICKER

### ISSUE THREAD

**Issue by Princeuby** [Princeuby/ASec#15]
A date picker that can work on any browser is needed

**Comment by BrainMaestro** [comment]
This thing is complicated

**Comment by BrainMaestro** [comment]
Why did you put the datepickr javascript code in every page. You should have just put it in the footer like how I did the textarea. Also, it looks like there's code there that's not being used.

**Comment by tenorz007** [comment]
Then clean it up and stop complaining.

**Comment by BrainMaestro** [comment]
Leave it like that if you want. I'm not touching it
