### ISSUE TITLE
Create new user - AVP, Asst. Supervisor , ACSO 

### ISSUE THREAD

**Issue by Princeuby** [Princeuby/ASec#25]
AVP - Reports
CSO & ACSO - Same
Sen. Supervisor, Supervisor, Asst Supervisor (Same). However, the "Leave Request" function will be removed from the Asst. Supervisor.

**Comment by BrainMaestro** [comment]
What did we decide on Assistant Supervisor. Should they have their own controllers? or be identical to normal officers?

**Comment by Princeuby** [comment]
We decided that since their leave request pass through the supervisor as well then they are identical to normal officers

**Comment by BrainMaestro** [comment]
Okay it's done then.
